export default {
  "login": "AliAksoyy",
  "id": 106846101,
  "node_id": "U_kgDOBl5XlQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/106846101?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AliAksoyy",
  "html_url": "https://github.com/AliAksoyy",
  "followers_url": "https://api.github.com/users/AliAksoyy/followers",
  "following_url": "https://api.github.com/users/AliAksoyy/following{/other_user}",
  "gists_url": "https://api.github.com/users/AliAksoyy/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AliAksoyy/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AliAksoyy/subscriptions",
  "organizations_url": "https://api.github.com/users/AliAksoyy/orgs",
  "repos_url": "https://api.github.com/users/AliAksoyy/repos",
  "events_url": "https://api.github.com/users/AliAksoyy/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AliAksoyy/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ali Aksoy",
  "company": null,
  "blog": "https://www.linkedin.com/in/aliaksoyy/",
  "location": "Turkey",
  "email": null,
  "hireable": null,
  "bio": "I am a React / Javascript Developer with high-level motivation for learning. I excited to learn new things, develop and improve.",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 0,
  "followers": 56,
  "following": 90,
  "created_at": "2022-06-03T21:41:21Z",
  "updated_at": "2023-01-02T14:29:27Z"
  }